### ISSUE TITLE
gulp watch throws error

### ISSUE THREAD

**Issue by morsssss** [morsssss/amp-ecomm#7]
When I modify HTML, the build errors out:

[Browsersync] Serving files from: dist/
[10:52:48] Starting 'rebuild'...
[10:52:48] Starting 'build'...
[10:52:48] Starting 'images'...
[10:52:48] Finished 'images' after 135 ms
[10:52:48] Starting 'html'...
[10:52:48] Starting 'styles'...
[10:52:48] Finished 'styles' after 24 ms
[10:52:48] Starting 'buildHtml'...
[10:52:48] Finished 'buildHtml' after 2.16 ms
[10:52:48] Finished 'html' after 27 ms
[10:52:48] Starting 'validate'...
[10:52:48] The following tasks did not complete: default, <parallel>, watch, <series>, rebuild, build, validate
[10:52:48] Did you forget to signal async completion?
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write callback called multiple times
    at DestroyableTransform.afterTransform (/Users/morss/Sites/amp-ecomm/node_modules/readable-stream/lib/_stream_transform.js:84:31)
    at DestroyableTransform.fileInclude [as _transform] (/Users/morss/Sites/amp-ecomm/node_modules/gulp-file-include/lib/index.js:58:9)
    at DestroyableTransform.Transform._read (/Users/morss/Sites/amp-ecomm/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/morss/Sites/amp-ecomm/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/morss/Sites/amp-ecomm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/morss/Sites/amp-ecomm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/morss/Sites/amp-ecomm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at StreamFilter.ondata (/Users/morss/Sites/amp-ecomm/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at emitOne (events.js:116:13)
    at StreamFilter.emit (events.js:211:7)
~/Sites/amp-ecomm:$

@demianrenzulli ?  @garanj ? Want to take this on? 😬

**Comment by morsssss** [comment]
(if I modify CSS, the same thing happens)

**Comment by garanj** [comment]
oh no! Do you have example html / css for this?

**Comment by morsssss** [comment]
I get it right now with the master branch...

**Comment by garanj** [comment]
See https://github.com/morsssss/amp-ecomm/pull/12

Requires updating amphtml-autoscript 1.2.0
